executors:
  machine:
    environment:
      USER_NAME: pepsipu
      USER_EMAIL: pokeso123@hotmail.com
    ruby:
      version: 2.4.1
    node:
      version: 8.2.1

jobs:
  build:
    executor: machine
    steps:
      - checkout
      - run:
            name: Install node@6.2.2 (need right version for `yarn`)
            command: |
              set +e
              touch $BASH_ENV
              curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
              echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
              echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
              echo 'nvm install v8.2.1' >> $BASH_ENV
              echo 'nvm alias default v8.2.1' >> $BASH_ENV
      - run: gem install bundler
      - run: ./bin/setup
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
      - run: ./bin/automated