executors:
  docker:
    - image: circleci/node:8.0
    environment:
      USER_NAME: pepsipu
      USER_EMAIL: pokeso123@hotmail.com
    ruby:
      version: 2.4.1

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - run: sudo ls
      - run: gem install bundler
      - run: sudo npm install -g n
      - run: sudo n stable
      - run: ./bin/setup
      - run: bundle exec jekyll build
      - run: bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
      - run: ./bin/automated